### ISSUE TITLE
SceneView layout xml didn't display anything

### ISSUE THREAD

**Issue by albertusadrians** [SceneView/sceneview-android#179]
Hi, I'm Adrian. Right now i'm trying to build an application that combines ML Kit with Sceneview and AR Core. However, I've problem when trying to design the XML layout that calls io.github.sceneview.SceneView. This layout didn't show anything and give an error message like this "Failed to instantiate one or more class". Anyway, I'm using the latest Android Studio Dolphin  and I've already tried to compile project with java version 1.8 and it's still not working. Below is the detail of the stack:

java.lang.UnsatisfiedLinkError: no filament-jni in java.library.path: [C:\Program Files\Android\Android Studio\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\ProgramData\Anaconda3, C:\ProgramData\Anaconda3\Library\mingw-w64\bin, C:\ProgramData\Anaconda3\Library\usr\bin, C:\ProgramData\Anaconda3\Library\bin, C:\ProgramData\Anaconda3\Scripts, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\extras\CUPTI\lib64, C:\Program Files\Common Files\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\Java\jdk-18.0.2.1\bin, C:\Program Files\dotnet\, C:\Program Files\Git\cmd, C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.3.0\, D:\xampp\php, C:\ProgramData\ComposerSetup\bin, C:\Windows\system32\config\systemprofile\AppData\Roaming\Composer\vendor\bin, C:\Program Files\Cloudflare\Cloudflare WARP\, C:\Users\acer\AppData\Local\Microsoft\WindowsApps, C:\Users\acer\AppData\Local\Programs\Microsoft VS Code\bin, C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\bin, ., C:\Users\acer\.dotnet\tools, C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.1\bin, ., C:\Program Files\JetBrains\PyCharm 2022.2.1\bin, ., C:\AdditionalPackages\protoc-21.6-win64\bin, C:\Users\acer\AppData\Roaming\Composer\vendor\bin; C:\Users\acer\composer, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.google.android.filament.Filament.<clinit>(Filament.java:22)
	at com.google.android.filament.utils.Utils.init(Utils.kt:27)
	at io.github.sceneview.SceneView.<clinit>(SceneView.kt:759)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

I appreciate any help from you guys. Thanks a lot

![image](https://user-images.githubusercontent.com/90084693/200253848-028c1eff-7a9c-49d2-8056-daeb13dec286.png)

**Comment by grassydragon** [comment]
Hi!
Yes, we've also encountered this problem with the latest version of Android Studio.

**Comment by vigit3** [comment]
Just back to previous version

**Comment by albertusadrians** [comment]
Thank you guys for your suggestions. Can you tell me which version of Android Studio that support this sceneview? 

Because previously, I used sceneform with Android Studio Chipmunk, but the layout xml didn't show up

**Comment by vigit3** [comment]
I used this
android-studio-2021.2.1.16-windows

**Comment by grassydragon** [comment]
> Just back to previous version

Alternatively, it's possible to just comment out the `SceneView` tag when working with the layout.

**Comment by albertusadrians** [comment]
Thanks a lot for your solutions guys. I appreciate it

**Comment by albertusadrians** [comment]
I think right now there are 2 ways that we can do to handle this issue:
1. First, we can use previous version of Android Studio (Chipmunk)
2. Second, we can comment out Sceneview

**Comment by ThomasGorisse** [comment]
Hi,
The `isInEditMode()` will be handled in coming next version.

**Comment by albertusadrians** [comment]
> Hi, The `isInEditMode()` will be handled in coming next version.

Thank u so much, I'm really waiting for that
