### ISSUE TITLE
AR Model Viewer sample app crashed when moving 3d model

### ISSUE THREAD

**Issue by Mehequanna** [SceneView/sceneview-android#231]
I have a Pixel 3 and was testing out `samples.ar-model-viewer`. While moving the 3d model around the scene, the app crashes back to the Android Home Screen. I copied the full errors below. 

## Errors before crash
```
E/native: E0000 00:00:1677863171.553995   27106 hit_test.cc:428] INTERNAL: No point hit.
E/native: E0000 00:00:1677863171.567171   27106 hit_test.cc:428] INTERNAL: No point hit.
E/native: E0000 00:00:1677863171.583450   27106 hit_test.cc:428] INTERNAL: No point hit.


E/native: E0000 00:00:1677863171.735611   27106 status.cc:162] FAILED_PRECONDITION: 
    ARCoreError: third_party/arcore/ar/core/session.cc:3083
    
    ARCoreError: third_party/arcore/ar/core/session.cc:2964
     at third_party/arcore/ar/core/session.cc:2967Cannot create anchors attached to a paused or stopped trackable [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_NOT_TRACKING']
    === Source Location Trace: === 
    third_party/arcore/ar/core/status.cc:171
    third_party/arcore/ar/core/session.cc:2964
    third_party/arcore/ar/core/session.cc:3083
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback


E/MessageQueue-JNI: com.google.ar.core.exceptions.NotTrackingException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
        at com.google.ar.core.HitResult.nativeCreateAnchor(Native Method)
        at com.google.ar.core.HitResult.createAnchor(HitResult.java:1)
        at io.github.sceneview.ar.node.ArModelNode.onMoveEnd(ArModelNode.kt:336)
        at io.github.sceneview.gesture.GestureDetector$moveGestureDetector$1.onMoveEnd(GestureDetector.kt:257)
        at io.github.sceneview.gesture.MoveGestureDetector.onTouchEvent(MoveGestureDetector.kt:160)
        at io.github.sceneview.gesture.GestureDetector.onTouchEvent(GestureDetector.kt:328)
        at io.github.sceneview.SceneView.onTouchEvent(SceneView.kt:546)
        at android.view.View.dispatchTouchEvent(View.java:14540)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4196)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
        at android.view.View.dispatchPointerEvent(View.java:14799)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6344)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6145)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5623)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5811)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5868)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8558)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8509)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8478)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8681)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.sceneview.sample.armodelviewer, PID: 27106
    com.google.ar.core.exceptions.NotTrackingException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
        at com.google.ar.core.HitResult.nativeCreateAnchor(Native Method)
        at com.google.ar.core.HitResult.createAnchor(HitResult.java:1)
        at io.github.sceneview.ar.node.ArModelNode.onMoveEnd(ArModelNode.kt:336)
        at io.github.sceneview.gesture.GestureDetector$moveGestureDetector$1.onMoveEnd(GestureDetector.kt:257)
        at io.github.sceneview.gesture.MoveGestureDetector.onTouchEvent(MoveGestureDetector.kt:160)
        at io.github.sceneview.gesture.GestureDetector.onTouchEvent(GestureDetector.kt:328)
        at io.github.sceneview.SceneView.onTouchEvent(SceneView.kt:546)
        at android.view.View.dispatchTouchEvent(View.java:14540)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4196)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
        at android.view.View.dispatchPointerEvent(View.java:14799)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6344)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6145)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5623)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5811)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5868)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8558)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8509)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8478)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8681)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by hshapley** [comment]
Suggestion:
Instead of `anchor = lastTrackingHitResult?.createAnchor()` (ArModelNode line 336), I think simply calling `anchor()` would be better, since it is more robust (checks for isTracking and also attempts a hit test if the lastTrackingHitResult won't work).

**Comment by ThomasGorisse** [comment]
@Mehequanna Would you create a PR for fixing that?

**Comment by Mehequanna** [comment]
@hshapley That's the behavior I'm used to. Thanks for pointing it out.

@ThomasGorisse sure thing!

**Comment by Mehequanna** [comment]
Fixed in #261
