### ISSUE TITLE
FatalException not caught in ArModelNode createAnchor()

### ISSUE THREAD

**Issue by kmayoral** [SceneView/sceneview-android#236]
I have a stack trace crash log from a user that looks like this:
```
Fatal Exception: com.google.ar.core.exceptions.FatalException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
       at com.google.ar.core.HitResult.nativeCreateAnchor(HitResult.java)
       at com.google.ar.core.HitResult.createAnchor(HitResult.java:1)
       at io.github.sceneview.ar.node.ArModelNode.createAnchor(ArModelNode.kt:393)
       at io.github.sceneview.ar.node.ArModelNode.anchor(ArModelNode.kt:373)
       at io.github.sceneview.ar.node.ArModelNode.onArFrame(ArModelNode.kt:294)
       at io.github.sceneview.ar.ArSceneView.doArFrame(ArSceneView.kt:455)
       at io.github.sceneview.ar.ArSceneView.doFrame(ArSceneView.kt:413)
       at io.github.sceneview.SceneView.doFrame(SceneView.kt:478)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
       at android.view.Choreographer.doFrame(Choreographer.java:925)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

It looks like there is some ArStatus Exception in the Session at the time that the ArModelNode is attempting to create an anchor but unfortunately the cause does not appear to be bubbled up the stack trace. Looking at the trace though, it does appear that the session should be valid since we're triggering this anchor attempt from a `onArFrame()` callback which should only trigger when we have a session.

While I don't have a cause for the exception, perhaps we could change the following line to be more robust:

https://github.com/SceneView/sceneview-android/blob/01dbc88802f2032b72d883f3aed91ba69fa0944e/arsceneview/src/main/java/io/github/sceneview/ar/node/ArModelNode.kt#L393

to something like:
```
return try { hitResult?.createAnchor() } catch (e: Exception) { null } 
```

I don't have the full context of what may be going on so I only wanted to report this issue and let you decide in case my thinking is incorrect.

This issue was reported both in ARSceneView release 0.9.4 and 0.9.7.

Thank you again for a great library!

**Comment by kmayoral** [comment]
I forgot to mention that this appears to happen in the ArModelNode flow when instant anchor placement is enabled. I will be testing to see if I can resolve the issue in the short term by disabling this for now....

**Comment by Mehequanna** [comment]
I was looking into my bug/crash report I posted on #231 . After debugging, I got to the same bit of code `hitResult?.createAnchor() `. I agree we should make the line more robust with a try catch. I've been trying to think about what to do with the caught error. Also, in the sense of trying to update an anchor, what happens when the anchor isn't created? Should the model go back to where it was before?

**Comment by kmayoral** [comment]
Thanks for the comment @Mehequanna, and all good questions. It does look like the stack trace in your report was caused by a `NotTrackingException` at least whereas this was the more generic `FatalException` but the point still remains that it should probably be more robust in handling the error. I will defer to others to decide on the best behavior to implement for all of the questions you asked as I don't have enough context to know. I appreciate you looking at this issue and corroborating the problem!

**Comment by ThomasGorisse** [comment]
@kmayoral @Mehequanna Sorry for the late answer.
The `try catch` must be done on the user side in order to retrieve infos around the anchoring issue and possibly react in consequence (remove other anchors, ask the user to move,...)
<img width="774" alt="image" src="https://user-images.githubusercontent.com/6597529/229304568-07f76fa8-70e9-4b00-8328-b553cf3dd009.png">
