### ISSUE TITLE
Load Text View in Augmented Image with Scene View

### ISSUE THREAD

**Issue by nadine199177** [SceneView/sceneview-android#347]
Hello

 I am trying to load the  model and the text view at the corner of the augmented image , I am not able to load the text view just the map pointer, **there is not enough samples on augmented image, is there any sample on Sceneform that did the same** 
(besides the camera is running slow after loading the 3d model how to solve this)

```
  onSessionUpdated = { session, frame ->
                frame.getUpdatedAugmentedImages().forEach { augmentedImage ->
                    if (augmentedImageNodes.none { it.imageIndex == augmentedImage.index }) {
                        if (augmentedImageNodes2.none { it.imageIndex == augmentedImage.index }
                        ) {
                            val augmentedImageNode =
                                AugmentedImageNode(engine, augmentedImage).apply {
                                    addChildNode(
                                        ModelNode(
                                            modelInstance = modelLoader.createModelInstance(
                                                assetFileLocation = "models/map_pointer.glb"
                                            ),
                                            scaleToUnits = 0.1f,
                                            centerOrigin = null

                                        ))
                                }


                            val augmentedImageNode2 =
                                AugmentedImageNode(engine, augmentedImage).apply {
                                    addChildNode(
                                        ViewNode(
                                            engine,
                                            modelLoader,
                                            viewAttachmentManager = ViewAttachmentManager(
                                                context,
                                                view
                                            )
                                        ).apply {
                                            transform(
                                                scale = Scale(0.1f),
                                                position = Position(z = -4f),
                                                rotation = Rotation()
                                            )
                                            loadView(context,
                                                R.layout.view_node_layout)
                                        })
                                }
                            addChildNode(augmentedImageNode)
                            addChildNode(augmentedImageNode2)
                            augmentedImageNodes += augmentedImageNode
                            augmentedImageNodes2 += augmentedImageNode2
                        }
                    }
                }
```

**Comment by pablojoseoroz** [comment]
Hi @nadine199177, I suggest you to create ViewAttachmentManager onViewCreated and call his onResume and onPause in your fragment lifecycle methods. Then use it as property when add ViewNode

**Comment by nadine199177** [comment]
not working got this, only model loading is working 

```
[49119] aiie.l(30): Error while reading encrypted model
                                                                                                    java.security.GeneralSecurityException: decryption failed
                                                                                                    	at aqoy.a(PG:134)
                                                                                                    	at aiie.l(PG:17)
                                                                                                    	at zbg.apply(PG:52)
                                                                                                    	at j$.util.Optional.map(SourceFile:17)
                                                                                                    	at ahmp.<init>(PG:80)
                                                                                                    	at agju.apply(PG:114)
                                                                                                    	at j$.util.stream.s.accept(SourceFile:44)
                                                                                                    	at j$.util.stream.s.accept(SourceFile:66)
                                                                                                    	at j$.util.a.forEachRemaining(SourceFile:20)
                                                                                                    	at j$.util.stream.c.y(SourceFile:21)
                                                                                                    	at j$.util.stream.G.a(SourceFile:10)
                                                                                                    	at j$.util.stream.c.K(SourceFile:35)
                                                                                                    	at j$.util.stream.C1.forEach(SourceFile:10)
                                                                                                    	at ahgx.a(PG:397)
                                                                                                    	at apye.e(PG:3)
                                                                                                    	at apyg.run(PG:42)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at nvr.run(PG:147)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
2023-11-13 11:04:35.824 31962-32007 Finsky                  pid-31962                            E  [49119] ahmd.apply(178): Error occurred in background task PostInstallVerificationTask
                                                                                                    com.google.android.finsky.verifier.impl.gramophone.RuleParseException: Failed to parse rule
                                                                                                    	at agon.al(PG:123)
                                                                                                    	at agon.al(PG:209)
                                                                                                    	at amhe.<init>(PG:25)
                                                                                                    	at ahmm.accept(PG:249)
                                                                                                    	at j$.util.Optional.ifPresent(Unknown Source:4)
                                                                                                    	at ahmp.<init>(PG:112)
                                                                                                    	at agju.apply(PG:114)
                                                                                                    	at j$.util.stream.s.accept(SourceFile:44)
                                                                                                    	at j$.util.stream.s.accept(SourceFile:66)
                                                                                                    	at j$.util.a.forEachRemaining(SourceFile:20)
                                                                                                    	at j$.util.stream.c.y(SourceFile:21)
                                                                                                    	at j$.util.stream.G.a(SourceFile:10)
                                                                                                    	at j$.util.stream.c.K(SourceFile:35)
                                                                                                    	at j$.util.stream.C1.forEach(SourceFile:10)
                                                                                                    	at ahgx.a(PG:397)
                                                                                                    	at apye.e(PG:3)
                                                                                                    	at apyg.run(PG:42)
```

**Comment by nadine199177** [comment]
when I set the background color of the text view to green the whole screen turns green 
```

 var augmentedtextNode =
                                AugmentedImageNode(engine, augmentedImage).apply {
                                    addChildNode(
                                        ViewNode(
                                            engine,
                                            modelLoader
                                            ,viewAttachmentManager
                                        ).apply {

                                            loadView(
                                                requireContext(),
                                                R.layout.view_node_layout).apply {
                                                transform(
                                                    scale = Scale(0.5f),
                                                    position = Position(0.0f),
                                                    rotation = Rotation()
                                                )
                                                setBackgroundColor(Color.GREEN)}
                                        }
                                    )
                                }
```

**Comment by pablojoseoroz** [comment]
Hi @nadine199177, I recommend you to add ViewNode to other Node when 
`this.onViewLoaded = { renderableInstance, view ->`
completed, else often it won't be visible.
Furthermore, for your example, I suggest you to add ViewNode when recognise it on 
`private fun onSeessionUpdated(session: Session, frame: Frame) {`
Good luck ;-)
