### ISSUE TITLE
Lifecycle crash when BackPressed on Fragment.

### ISSUE THREAD

**Issue by NupeAI** [SceneView/sceneview-android#358]
FATAL EXCEPTION: main
                                                                                                    Process: com.btechlabs.inlayer, PID: 9304
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property colorGrading has not been initialized
                                                                                                    at io.github.sceneview.SceneView.destroy(SceneView.kt:698)
                                                                                                    at io.github.sceneview.SceneView$setLifecycle$1.onDestroy(SceneView.kt:731)
                                                                                                    at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:29)
                                                                                                    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                                                    at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.kt:266)
                                                                                                    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:283)
                                                                                                    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
                                                                                                    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
                                                                                                    at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3372)
                                                                                                    at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:812)
                                                                                                    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
                                                                                                    at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
                                                                                                    at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
                                                                                                    at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.kt:774)
                                                                                                    at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.kt:150)
                                                                                                    at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.kt:101)
                                                                                                    at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.kt:234)
                                                                                                    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1956)
                                                                                                    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
                                                                                                    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
                                                                                                    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
                                                                                                    at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    at android.os.Looper.loop(Looper.java:288)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

2023-11-27 10:30:41.300  9304-9304  Filament                com.btechlabs.inlayer,       E  in destroy:1002
                                                                                                    reason: destroying material "base_lit_opaque" but 9 instances still alive
2023-11-27 10:30:41.300  9304-9304  Filament                com.btechlabs.inlayer,       E  
2023-11-27 10:30:41.300  9304-9304  Filament               com.btechlabs.inlayer,       E  in destroy:1002
                                                                                                    reason: destroying material "base_lit_fade" but 5 instances still alive

**Comment by NupeAI** [comment]
@ThomasGorisse Is there anything you can do about this or guidance? I see in SceneView.kt line 446 to 449 have been commented out.

// colorGrading = ColorGrading.Builder().toneMapping(ColorGrading.ToneMapping.FILMIC).build(engine)
// filamentView.colorGrading = colorGrading

I am using version 2.0.0

implementation("io.github.sceneview:sceneview:2.0.0")

Thank you
