### ISSUE TITLE
 How to load glb model from internal storage?

### ISSUE THREAD

**Issue by David7145g** [SceneView/sceneview-android#381]
I'm downloading models from the server. So I can't put them in Assets.
Code:
`modelLoader.createInstancedModel(urlFile3dModel, 10)`
Error:
 Caused by: java.io.FileNotFoundException: 
 /data/user/0/com.arcore/files/66632267-4ccf-4f4b-89ca-77c568457e46.glb
at android.content.res.AssetManager.nativeOpenAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:881)
at android.content.res.AssetManager.open(AssetManager.java:858)

**Comment by David7145g** [comment]
```
val file = File(urlFile3dModel)
this += modelLoader.createInstancedModel(file, 10)
```
