### ISSUE TITLE
ARScene crashes on compose when disposing element

### ISSUE THREAD

**Issue by jopakka** [SceneView/sceneview-android#440]
I have switch to toggle ARScene and other composable view. ARScene crashes when it should be disposed. I test it with code from README.md and it happens with that also.

```
@Composable
fun ArCoreView() {
    val engine = rememberEngine()
    val modelLoader = rememberModelLoader(engine)
    val model = modelLoader.createModel("target.glb")
    var frame by remember { mutableStateOf<Frame?>(null) }
    val childNodes = rememberNodes()
    ARScene(
        modifier = Modifier.fillMaxSize(),
        engine = engine,
        modelLoader = modelLoader,
        onSessionUpdated = { session, updatedFrame ->
            frame = updatedFrame
        },
        onGestureListener = rememberOnGestureListener(
            onSingleTapConfirmed = { motionEvent, node ->
                val hitResults = frame?.hitTest(motionEvent.x, motionEvent.y)
                val anchor = hitResults?.firstOrNull {
                    it.isValid(depthPoint = false, point = false)
                }?.createAnchorOrNull()

                if (anchor != null) {
                    val anchorNode = AnchorNode(engine = engine, anchor = anchor)
                    anchorNode.addChildNode(
                        ModelNode(modelInstance = modelLoader.createInstance(model)!!)
                    )
                    childNodes += anchorNode
                }
            }
        ),
        childNodes = childNodes,
    )
}
```

```
var useAr by remember { mutableStateOf(false) }
if (useAr) {
    ArCoreView()
} else {
// Composable...
}
```

Logcat log:
```
CameraStream destroyed
Engine destroyed
E0000 00:00:1710399489.381480   24041 error_policy_util.cc:263] 
################ ARCore Native Error ##################
BUILD_CHANGELIST:585206826
BUILD_BASELINE_CHANGELIST:579924725
################### Stack Trace Begin ################
ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:1073	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/android_data_source.cc?g=0&l=1073
ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:534	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/android_data_source.cc?g=0&l=534
ARCoreError: third_party/arcore/ar/core/session.cc:1836	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1836
ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:76	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=76
################### Stack Trace End #################

################### Undecorated Trace Begin  #################
FAILED_PRECONDITION: 
ARCoreError: third_party/arcore/ar/core/session.cc:1836

ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:534

ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:1073
The subsystem Image is not started, expected to be started.
=== Source Location Trace: ===
third_party/arcore/ar/infrastructure/android_data_source.cc:1073
third_party/arcore/ar/infrastructure/android_data_source.cc:534
third_party/arcore/ar/core/session.cc:1836

################### Undecorated Trace End  #################
Shutting down VM
FATAL EXCEPTION: main
Process: io.fieldsight.app, PID: 24041
com.google.ar.core.exceptions.FatalException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
    at com.google.ar.core.Session.nativeUpdate(Native Method)
    at com.google.ar.core.Session.update(Session.java:2)
    at io.github.sceneview.ar.arcore.ARSession.updateOrNull(ArSession.kt:103)
    at io.github.sceneview.ar.ARSceneView.onFrame(ARSceneView.kt:464)
    at io.github.sceneview.SceneView$FrameCallback.doFrame(SceneView.kt:814)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1317)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
    at android.view.Choreographer.doCallbacks(Choreographer.java:985)
    at android.view.Choreographer.doFrame(Choreographer.java:911)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by AlexDarigan** [comment]
Testing this too on Samsung A23, I removed everything except the ARScene Composable itself and the crash persists.
