### ISSUE TITLE
java.lang.AssertionError: Unable to create RenderableInstance. 

### ISSUE THREAD

**Issue by morhenny** [SceneView/sceneview-android#45]
I ran into a new exception today that caused my app to crash, but only has happened this one time. Since I wasn't at home and not connected to Logcat, I don't quite remember all the details and only have this one final stack trace from my logfile:

```
2022-03-15 15:03:39.500 E/FATAL: A fatal crash caused the app to stop   
 java.lang.AssertionError: Unable to create RenderableInstance.  
   at com.google.ar.sceneform.rendering.RenderableInternalData.buildInstanceData(RenderableInternalData.java:229)  
   at com.google.ar.sceneform.rendering.RenderableInstance.prepareForDraw(RenderableInstance.java:488)  
   at com.google.ar.sceneform.rendering.Renderer.updateInstances(Renderer.java:668)  
   at com.google.ar.sceneform.rendering.Renderer.render(Renderer.java:314)  
   at io.github.sceneview.SceneView.doFrame(SceneView.kt:297)  
   at io.github.sceneview.ar.ArSceneView.doFrame(ArSceneView.kt:246)  
   at io.github.sceneview.SceneView.doFrame(SceneView.kt:291)  
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)  
   at android.view.Choreographer.doCallbacks(Choreographer.java:1149)  
   at android.view.Choreographer.doFrame(Choreographer.java:1040)  
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)  
   at android.os.Handler.handleCallback(Handler.java:938)  
   at android.os.Handler.dispatchMessage(Handler.java:99)  
   at android.os.Looper.loop(Looper.java:233)  
   at android.app.ActivityThread.main(ActivityThread.java:8068)  
   at java.lang.reflect.Method.invoke(Native Method)  
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)  
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

As far as I remember, I was already using my app for around 5-10 Minutes when it happened and the error (I think) occurred right when placing another 3d model, after having already placed quite a few within the same scene (~15 objects).

I was using the 0.1.0 version of sceneview when the bug happened and was hoping maybe someone had some insights as to what this could be caused by.

On a sidenote that might be related: I am not using `ArModelNodes` and their loadModel function, but I am loading my 3d models in advance and holding a reference within my code to those renderables and then setting them with `ArNode.setModel`. Since I have never had any issues with this, I doubt it is the cause, but I figured it could still be relevant to the exception.

**Comment by ThomasGorisse** [comment]
Thanks for the report.
It's a Renderable issue.
We still have work to do in order to clean it.

**Comment by ThomasGorisse** [comment]
You can follow the development status here: #44
