### ISSUE TITLE
Crash on disposing AR Scene in 2.1.0

### ISSUE THREAD

**Issue by dwane13** [SceneView/sceneview-android#468]
Device: Galaxy S23 U
Android V: 14

Not reproducing in 2.0.3

Steps:
1. Enter screen with AR
2. Load ArScene composable
3. Exit screen

Log:

`java.lang.NullPointerException
                                                                                                    	at io.github.sceneview.components.CameraComponent$DefaultImpls.getCamera(CameraComponent.kt:30)
                                                                                                    	at io.github.sceneview.node.CameraNode.getCamera(CameraNode.kt:27)
                                                                                                    	at io.github.sceneview.node.CameraNode.destroy(CameraNode.kt:330)
                                                                                                    	at [io.github.sceneview.ar](http://io.github.sceneview.ar/).ARSceneKt$rememberARCameraNode$$inlined$rememberNode$1$1.dispose(Effects.kt:498)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:87)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1276)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:639)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1069)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

Looks like that `!!` was mistake.

**Comment by Joseph-Hui** [comment]
A similar issue is mentioned [here](https://github.com/SceneView/sceneview-android/issues/450#issue-2215016262) and the author has no problem with version 2.0.4. In version 2.0.4, the `!!` has been there already. Possibly, there is a problem when destroying the `engine`.

https://github.com/SceneView/sceneview-android/blob/69d191b8d4f0f3f3564fc3591e1b5f007326e11a/sceneview/src/main/java/io/github/sceneview/components/CameraComponent.kt#L30
