### ISSUE TITLE
on destroy error

### ISSUE THREAD

**Issue by kennethverhoeven** [SceneView/sceneview-android#59]
hello, when using sceneview to display an object everything works great until you leave the activity and onDestroy gets called

i cloned the project and in sceneview.kt i commented this in the override destroy

override fun onDestroy(owner: LifecycleOwner)
 {
        super.onDestroy(owner)
        //renderer.destroyAllResources()
        //camera.destroy()
        //environment?.destroy()
        environment = null
        //mainLight?.destroy()
        mainLight = null
    }

after doing this everything works perfectly, if you could change this in the real git repository or find a better way to fix it that would be great, if you want me to push my version ill do that, i just dont want to accidentally break something

**Comment by grassydragon** [comment]
Hi!
What is the exception that you see? Can you open the `Activity` again?

**Comment by kennethverhoeven** [comment]
Hello, when i changed it back to get the error it still worked so im a bit confused right now, it still crashes when i use the official dependency. (when i made a module of it so i could edit it i also had to comment out a bunch of stuff like

id 'filament-tools-plugin'
id 'org.jetbrains.dokka' 

in the build.gradle file of sceneview itself because android studio couldnt find them)

this is the error i get

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kenneth.kaboekie, PID: 32350
    java.lang.RuntimeException: Unable to destroy activity {com.kenneth.kaboekie/com.kenneth.kaboekie.ui.RandomStuff}: java.lang.IllegalStateException: Calling method on destroyed Engine
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5675)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5720)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: Calling method on destroyed Engine
        at com.google.android.filament.Engine.getNativeObject(Engine.java:661)
        at com.google.android.filament.Engine.destroyIndirectLight(Engine.java:533)
        at io.github.sceneview.environment.IndirectLightKt.destroy(IndirectLight.kt:15)
        at io.github.sceneview.environment.Environment.destroy(Environment.kt:64)
        at io.github.sceneview.SceneView.onDestroy(SceneView.kt:274)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:51)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at io.github.sceneview.SceneView.parentLifecycleObserver$lambda-0(SceneView.kt:86)
        at io.github.sceneview.SceneView.$r8$lambda$VdyLiPAL1EzkEFreGKIq-a7OnsI(Unknown Source:0)
        at io.github.sceneview.SceneView$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:2)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:224)
        at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1532)
        at android.app.Activity.performDestroy(Activity.java:8464)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5660)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5720) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by ThomasGorisse** [comment]
Thanks for the feedback. It's a wrong destroy order issue.

It has been fixed here: fd4a440260f8a486c6f08f9d40a810c846ddbab7 - Fix exception on onDestroy

Can you check that if your issue is fixed with it?

Anyone has an idea on how to disable an `apply plugin` at the app level `build.gradle` when the depency classthpath is not defined in the root `build.gradle`?

**Comment by kennethverhoeven** [comment]
i tested it and i still get the same error

**Comment by StevenMOG** [comment]
I can verify this error with the current 0.4.1 arsceneview artifact.

**Comment by ThomasGorisse** [comment]
It must be a double destroy call issue.
@StevenMOG Can you check why the onDestroy() is called twice?

**Comment by StevenMOG** [comment]
I'll try to figure out when and why it happens. I never had this issue while developing with the sample apps but in our "real" app it happens sometimes.

**Comment by ThomasGorisse** [comment]
I'm on it. I'm removing all the old Filament Engine Wrapper with destroys in all the ways without really knowing when they are called.
We will have a Filament engine retainer that destroy everything only once when no SceneView need it anymore.
The only conterpart will that if a SceneView is destroyed and then recreated, the Filament Engine will also be.
