### ISSUE TITLE
java.lang.IllegalStateException: no event up from DESTROYED

### ISSUE THREAD

**Issue by ninjz** [SceneView/sceneview-android#73]
I have a Fragment which displays a SceneView and then a Dialog Fragment is displayed on top of it which contains another SceneView. The Dialog is then closed which then results in this crash.

Here is the stack trace:
```
FATAL EXCEPTION: main
Process: app.xxxxx.dev, PID: 5388
java.lang.IllegalStateException: no event up from DESTROYED
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:263)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
	at io.github.sceneview.SceneView.parentLifecycleObserver$lambda-0(SceneView.kt:77)
	at io.github.sceneview.SceneView.lambda$VdyLiPAL1EzkEFreGKIq-a7OnsI(Unknown Source:0)
	at io.github.sceneview.-$$Lambda$SceneView$VdyLiPAL1EzkEFreGKIq-a7OnsI.onStateChanged(Unknown Source:2)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at io.github.sceneview.SceneView.onAttachedToWindow(SceneView.kt:252)
	at android.view.View.dispatchAttachedToWindow(View.java:20812)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.attachView(ViewController.java:208)
	at com.reactnativenavigation.viewcontrollers.modal.ModalPresenter.dismissModal(ModalPresenter.java:100)
	at com.reactnativenavigation.viewcontrollers.modal.ModalStack.dismissModal(ModalStack.java:70)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.dismissModal(Navigator.java:196)
	at com.reactnativenavigation.react.NavigationModule.lambda$dismissModal$9$NavigationModule(NavigationModule.java:164)
	at com.reactnativenavigation.react.-$$Lambda$NavigationModule$K6INt9hfoIC5qsY-5Qqg9HQA-Bc.run(Unknown Source:10)
	at com.reactnativenavigation.react.NavigationModule.lambda$handle$13$NavigationModule(NavigationModule.java:199)
	at com.reactnativenavigation.react.-$$Lambda$NavigationModule$5N1_9vuln3JXRnlJ810xNwkxdsA.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I'm not sure what's causing this, but I'm thinking it might be the way i'm using the lifecycle?

Here is how i'm using SceneView within a FrameLayout inside of a Fragment:
```java
class RNTExerciseViewKt(context: Context, lifecycle: Lifecycle, reactContext: ReactContext, reactNativeViewId: Int) : FrameLayout(context) {
    private val sceneView = SceneView(context)
    private val cameraOrbit = Node()
    private var modelNode = ModelNode()

    private lateinit var camera: Camera
    private var currentlyPlaying: ObjectAnimator? = null

    init {
        this.addView(sceneView)

        sceneView.addChild(modelNode)
        lifecycle.coroutineScope.launchWhenCreated {
            sceneView.environment = KTXLoader.loadEnvironment(
                context = context,
                lifecycle = lifecycle,
                iblKtxFileLocation = "environments/default_environment_ibl.ktx",
                skyboxKtxFileLocation = null
            )
            ...
        }
    }
}
```

**Comment by code76kb** [comment]
> 
@ninjz  did you find anything on this issue, having same problem
